### ISSUE TITLE
project proposal

### ISSUE THREAD

**Issue by gui-rangel** [gui-rangel/fss16gui#9]
For the big project, I plan on working with the [TravisTorrent](http://2017.msrconf.org/#/challenge) dataset. 

One of my ideas was to do feature selection to see which features best help to predict whether a build is gonna fail, error, or pass. 

Another idea, in addition to the above, is to look at which prediction algorithms have better results for this specific type of data, potentially tune them.

**Comment by gui-rangel** [comment]
Papers to read: http://arxiv.org/pdf/1512.01862.pdf
https://pure.tue.nl/ws/files/3855750/621462246551620.pdf
http://web.cs.ucdavis.edu/~filkov/papers/pr_soc_lan.pdf

**Comment by timm** [comment]
better get going quick then on data download and feature extraction. u want that DONE before the big project starts otherwise u will run out of time

also, be realistic regarding data set size. chase 1% of the data and see how big it is. if HUGE then find some stratification that limits data size to something manageable.

**Comment by gui-rangel** [comment]
The full csv file is 1.77 gigabytes, so I might indeed have to get a portion of it.

I was gonna work more on the description before showing it to you, but anyhow. As I thought that just doing feature extraction would be considered too little for the _big project_, I had the idea of doing a more in-depth analysis of applying different algorithms to predict whether the build passes/fails. What do you think? is it too much/too little for the big project? And also, would it be enough for a 4-pages MSR Challenge submission?

**Comment by timm** [comment]
> was gonna work more on the description before showing it to you, 

so sorry i jumped the queue. you want me to get back to this is a few days.

re msr challenge: depnds if if improves on state of the art.
